---
- name: Basic Troubleshooting BGP
  hosts: veos1
  gather_facts: false
  vars:
    switches:
      - ping 10.0.0.1
      - ping 10.0.0.4

  tasks:

    - name: BGP Check
      arista.eos.eos_command:
       commands: show ip bgp summary vrf all
      register: bgp_summary

    - name: Check reachability of switches
      arista.eos.eos_command:
       commands: "{{ switches }}"
      register: result

    - set_fact:
       cacheable: true
       bgp_view: "{{ bgp_summary }}"
       bgp_ping: "{{ result }}"
       status: done
       bgp_state: "{{ ansible_eda.event.fields.session_state }}"
       bgp_prob_neighbor: "{{ ansible_eda.event.tags.neighbor_address }}"
       bgp_timestamp: "{{ ansible_eda.event.timestamp }}"
       bgp_error_type: "{{ ansible_eda.event.tags.identifier }}"
