- name: Hello Events
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: telegraf-kafka
        port: 29192
        topic: telegraf
  rules:
    - name: BGP change detected
      condition: event.body.fields.session_state == "IDLE"
      action:
        run_playbook:
          name: troubleshoot_bgp.yml
