- name: Hello Events
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: telegraf-kafka
        port: 29192
        topic: telegraf
  rules:
     - name: BGP change detected
       condition: event.fields.session_state == "IDLE"
       action:
        debug:
          msg: "{{ event.body }}"

