- name: Hello Events
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: telegraf-kafka
        port: 29192
        topic: telegraf
  rules:
    - name: Check cpu idle
      action:
        debug:
          msg: "{{ event.body }}"

